### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by quasiperfect** [brianwozeniak/codeigniter-modular-extensions-hmvc#1]
is this working with ci3 (latest github version) ?
is this working with default_controller, 404_override and translate_uri_dashes ?

i'm asking because i tried with a default instalation of ci3 and i get a 404 instead of welcome

**Comment by rickerd** [comment]
I havent tried it with CI3
But this is also because there isnt a full version of CI3.
Better wait untill they bake us a full a CI3 instead an CI2.9-3 to test and adjust code.

---

Met vriendelijke groet,
Rick de Graaff

Verstuurd vanaf mijn iPhone 4S

Op 28 aug. 2013 om 17:52 heeft "quasiperfect" notifications@github.com het volgende geschreven:

**Comment by quasiperfect** [comment]
hmm it seams it works only if i set $remove_default_routes = FALSE;
i want to remove the default routes (controllers routes) but keep default_controller, 404_override and translate_uri_dashes

another thing if you don't have any modules you get a error because the $directories will not be a array so after every $directories = $this->module_map(); add $directories = (!is_array($directories))?array():$directories;
or force module_map to return a array

another problem i found if i enable the profiler ($this->output->enable_profiler(TRUE);) inside a controller i get Undefined property: CI::$Profiler

**Comment by brianwozeniak** [comment]
I have not tested this at all with CI3, only the latest CI2 version. I probably won't put any time into getting this to work with CI3 until it has been released due to all the changes that will most likely continue to happen on their end.

**Comment by quasiperfect** [comment]
i will test and try to fix the problems i find 
don't expect to much changes, unless someone takes over, 3 will never happen

**Comment by quasiperfect** [comment]
i tried again with ci 2.1.4 and i get the same problem it doesn't take in account default_controller is this intentional or a bug ?

**Comment by brianwozeniak** [comment]
What is your default_controller set to? Do you have an example where I can see this in action? Everything works for me as far as I can tell, but its possible there is a bug of some sorts. Here is my default controller that works for me:

$route['default_controller'] = "home_controller/index";

and then I have a file in controllers called:

home_controller.php

that starts out like:

```
class Home_Controller extends MX_Controller {

    function index() {
        echo "Works!";
    }
}
```

**Comment by quasiperfect** [comment]
@Bigwebmaster with $remove_default_routes set to false default controller works with true i get a 404

**Comment by brianwozeniak** [comment]
I have $remove_default_routes set to TRUE and it works for me. Can you provide more information on what your default_controller is set to, and what your controller that should be loading basically looks like. There has to be something else contributing to the issue.

**Comment by quasiperfect** [comment]
after some testing i isolated the problem

in mx/router.php you have

```
if ($this->remove_default_routes && !$module_source && empty($routes) && (!in_array($uri, array_values($this->routes))))
{
      return;
}
```

so you force me to declare the route like welcome/index and if i have another function i have to declare a new route welcome/function

i want to use something like 

```
$route['controller(.*)'] = "controller$1";
```

edit:

so i created a new function

```
function _validate_my_route($uri)
  {
    if (isset($this->routes[$uri]))
    {
      return TRUE;
    }

    foreach ($this->routes as $key => $val)
    {
      $key = str_replace(':any', '.+', str_replace(':num', '[0-9]+', $key));
      if (preg_match('#^' . $key . '$#', $uri))
      {
        return TRUE;
      }
    }
    return FALSE;
  }
```

and changed the condition  (!in_array($uri, array_values($this->routes)) to !$this->_validate_my_route($uri)

**Comment by brianwozeniak** [comment]
Thanks for the explanation, I understand what you were trying now. I have verified that problem does exist.

**Comment by quasiperfect** [comment]
@Bigwebmaster my final function is

```
function _validate_my_route($uri)
  {
    if (isset($this->routes[$uri]))
    {
      return TRUE;
    }

    $first_segment = explode('/', $uri);
    $first_segment = $first_segment[0];

    if ($this->default_controller == $first_segment)
    {
      return TRUE;
    }

    foreach ($this->routes as $key => $val)
    {
      $key = str_replace(':any', '.+', str_replace(':num', '[0-9]+', $key));

      if (preg_match('#^' . $key . '$#', $uri))
      {
        return TRUE;
      }
    }
    return FALSE;
  }
```

**Comment by brianwozeniak** [comment]
Looks like you almost have it, there are a few issues I see after some initial tests. Part of the problem/confusion that I see is that $uri you are treating as the real URI, when it actually its a translated route already. For example in my case of testing the true URI is "form", but $uri has the value of "form_controller/index". I need to update that variable to reflect what it truly is, and then update your code to handle it correctly.

Thanks for pointing it all out though and giving me a good start for the solution.

**Comment by quasiperfect** [comment]
i'm not sure i understand what you say but to be honest i never got over all the mx code
i will wait to see your modifications
if you are so kind and have a good understanding of ci's routing process can you pseudocode (file (function)->to file(function) etc ) that for me (if is not to much time consuming for you) ?

**Comment by brianwozeniak** [comment]
I am not sure I am understanding exactly what you want pseudocoded there?

**Comment by quasiperfect** [comment]
the steps a request takes in the routing system (i will look at the entire code but some info from someone that already did that would be of great help)

**Comment by brianwozeniak** [comment]
I still have more testing, to do, but I think this may work correctly:

```
private function _validate_route($routed) {

    // Break down all the segments of our translated route
    $routed_segments = explode('/', $routed);

    // Do we have a match with our default controller?
    if ($this->default_controller == $routed || $this->default_controller == $routed_segments[0]) {
        return TRUE;
    }

    // Turn the URI segment array into a URI string
    $uri = implode('/', $this->uri->segments);

    // Go through each route and see if it matches with wildcards
    foreach ($this->routes as $key => $val) {
        $key = str_replace(':any', '.+', str_replace(':num', '[0-9]+', $key));

        if (preg_match('#^' . $key . '$#', $uri))   {               
            return TRUE;
        }
    }

    // Finally do we have a match with a 404 override?
    if(isset($this->routes['404_override']) AND $this->routes['404_override'] == $routed) {
        return TRUE;            
    }

    return FALSE;
}
```

**Comment by namcoding** [comment]
copy default controller, default model defaulf view in modules to controller folder default CI3, it working :3
