### ISSUE TITLE
language uri + remove default routes

### ISSUE THREAD

**Issue by quasiperfect** [brianwozeniak/codeigniter-modular-extensions-hmvc#2]
any idea how to combine this with the language uri solution ?

**Comment by brianwozeniak** [comment]
Are you referring to having a URL like:

http://yourdomain.com/en/somepage

If so I have not done any work testing to see if that is possible. It likely will need further work by somebody.

**Comment by quasiperfect** [comment]
yea that's what i wanted
for now i solved the problem using htaccess like this 

```
RewriteCond %{REQUEST_URI} !/[a-z]{2}/|(^/[a-z]{2}$)  [NC]
RewriteRule ^(.*)$ http://%{HTTP_HOST}/en%{REQUEST_URI} [L]
```

**Comment by quasiperfect** [comment]
if anyone is interested it works with some modification to routes and removal of default routes you can even have
translated routes like
http://www.domain.ext/en/welcome
http://www.domain.ext/it/benvenuto
without renaming controllers
