### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by dcboy** [brianwozeniak/codeigniter-modular-extensions-hmvc#4]
hi
when i use $this->load->module('xxx') fail!
example
modules
   ----m1
     ---controllers
         ---c.php
               has function name  test()
   ----m2
     ---controllers
         ---c.php
               has function name test2()

when in modules "m2" controller "c" test2 call
$m1= $this->load->module('m1/c');
then call $m1->test();
error not define c::test();

why? how to fix?

thx!

**Comment by brianwozeniak** [comment]
Is the name of your class in c.php m1? Make sure the class name matches.

**Comment by dcboy** [comment]
the class name is matches
m1 is folder c.php  is 
      class c extend MX_Controller
m2 is folder c.php is
     class c extend MX_Controller

**Comment by brianwozeniak** [comment]
Your class name needs to be m1 for your example to work. Instead of doing this:

$m1= $this->load->module('m1/c');

You might try:

$this->load->module('m1');

$this->m1->method();

**Comment by dcboy** [comment]
m1 is not class that is module folder!

**Comment by brianwozeniak** [comment]
If your controller file is c then, set your class name as c.

Please read the documentation for full examples how to set this up. This is not a bug.
