### ISSUE TITLE
Multiple controllers in a Module

### ISSUE THREAD

**Issue by AaronLayton** [brianwozeniak/codeigniter-modular-extensions-hmvc#5]
I am trying to create an Admin module, that has routes for 

/Admin
`class Admin extends CI_Controller {`

/Admin/User
`class User extends CI_Controller {`

But of course this won't work because the User controller does not match the Module name. Any ideas how I can create my Admin as a single module I can just drop in?

I can get the User page loaded but it won't pass in any URI segments

/admin/user/123/add <-- this doesn't work
/admin/user/ <-- this does

**Comment by brianwozeniak** [comment]
You should extend MX_Controller.

Also what does your routing file look like for this:

/admin/user/123/add <-- this doesn't work

**Comment by AaronLayton** [comment]
I was trying not to change the /application/config/routes.php file as I wanted this to be self contained. I realise the above may not be enough info though so let me try to clear it up.

I have the following
`/application/modules/admin/controllers/admin.php` all of the methods in there seem to work fine

if I add
`/application/modules/admin/controllers/users.php` then I can successfully goto
`http://localhost/admin/users`
This is picking up the index method inside the users controller. I can add in other methods into the user controller, for example
`public function edit($id)` and then I can goto `/admin/users/edit/:num'

My issue seems to be the index method in users does not allow me to route the ID to it. So I wont be able to use the following URL structure
`/admin/users/23` .. to edit a user

**Comment by brianwozeniak** [comment]
I think I understand what you are trying to do. What is your exact route you have specified in your routing file, the entire line that would relate to Users.

**Comment by AaronLayton** [comment]
None, nothing extra added to it. If I understand it right then the HMVC should just route the normal routes through to the modules?

**Comment by brianwozeniak** [comment]
If you want to be able to pass parameters you will probably need to add a route file inside the module (would still be able to just drop it in since this routes.php file is part of the module). In the route file you may need a line that looks something like:

```
$route['admin/users/(:any)'] = 'users/index';
```

That way it will accept any routes such as /admin/users/23
