### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by hArpanet** [brianwozeniak/codeigniter-modular-extensions-hmvc#6]
@Bigwebmaster are you still supporting development of this?

If so, do you have any plans for a CI v3.x compatible update?

(I'm currently trying to run it against CI 3.0-dev and finding some issues.)

Cheers.

**Comment by brianwozeniak** [comment]
I haven't had any updates lately, but am still here. Currently I haven't been doing anything for the 3.0 branch. If you decide to do any work feel free to fork off of this and I may incorporate some of what you do back in.
