### ISSUE TITLE
URI segments doesn't work

### ISSUE THREAD

**Issue by princeofforest** [brianwozeniak/codeigniter-modular-extensions-hmvc#7]
does the uri segment library doesn't work after using the the modular extension? so is there any alternative method?

**Comment by brianwozeniak** [comment]
It should work fine, can you provide me an example of code that is failing to work for you?

**Comment by princeofforest** [comment]
i have my uri library autoload, it returns this message, if i remove my autoload, it works fine. I am using codeigniter 2.2.0. thank you for the reply!
![screen shot 2015-03-02 at 12 06 22 pm](https://cloud.githubusercontent.com/assets/4649621/6449298/a9a685ae-c0d4-11e4-9924-cd240db7339e.jpg)

**Comment by princeofforest** [comment]
i have tried version 2.1.x, still getting the same error message, please advise.

**Comment by princeofforest** [comment]
Sorry, I just figure out the uri library has been loaded by the system, so i don't have to put it into the autoload array. thank you thank you
